config/routes.rb
StatusGitoriousOrg::Application.routes.draw do
  resources :statuses, :except => :destroy

  resources :sessions

  root :to => "statuses#current"
end

app/models/status.rb
class Status < ActiveRecord::Base
  OK = 1
  SORTA = 2
  DOWN = 3
  @@statuses = [OK, SORTA, DOWN]
  validates_presence_of :title, :status
  scope :problems, { :conditions => ["status in (2, 3)"], :order => "created_at desc" }

  attr_accessor :post_to_twitter

  def status=(code)
    code = code.to_i
    return self[:status] = code if @@statuses.include?(code)
    false
  end

  def status_text
    Status.status_text(status)
  end

  def self.current
    status = last
    raise ActiveRecord::RecordNotFound.new if status.nil?
    status
  end

  def self.last_problem
    problems.find(:first)
  end

  def self.status_text(status)
    status == OK && "Ok" || status == SORTA && "Sorta" || status == DOWN && "Down" || ""
  end

  def self.statuses
    @@statuses
  end

  @@statuses.each do |stat|
    define_method(:"#{Status.status_text(stat).downcase}?") { status == stat }
  end
end

app/models/twitter_update.rb
class TwitterUpdate
  attr_reader :status
  def initialize(status)
    @status = status
  end

  def message
    result = ""
    result << case status.status
              when Status::OK
                "[UP] "
              when Status::SORTA
                "[SOME ISSUES] "
              when Status::DOWN
                "[DOWN] "
              else
                ""
              end
    result << "#{status.title}"
    body =  status.body.blank? ? "" : ": #{status.body}" 
    remaining = (140 - result.size)
    if status.sorta?
      result << " Read more on http://status.gitorious.org/"
    else
      result << body unless body.size > remaining
    end
    result
  end

  def self.update
    required_keys = ["TWITTER_OAUTH_KEY","TWITTER_OAUTH_SECRET","TWITTER_CONSUMER_KEY","TWITTER_CONSUMER_SECRET"]
    if required_keys.all?{|key| ENV.has_key?(key)}
      yield
    end
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt
  validates_uniqueness_of :login
  
  def self.authenticate(login, password)
    user = find(:first, :conditions => {:login => login})
    !user.nil? && user.password == password ? user : nil
  end

  def password
    @password ||= Password.new(self[:password])
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self[:password] = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:login], params[:password])
      session[:current_user_id] = user.id
      redirect_to new_status_path
    else
      render :action => :new
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :login_required, :except => [:index, :current, :show]

  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def current
    @status = Status.current
    @created_at = @status.created_at.strftime('%Y-%m-%d %H:%M:%S')
    @problem = @status.ok? ? Status.last_problem : nil
    headers["X-Gitorious-Status-Code"] = @status.status_text
    headers["X-Gitorious-Status-Text"] = @status.title
  end

  def create    
    @status = Status.new(params[:status])
    if @status.post_to_twitter == "1"
      post_to_twitter(@status)
    end
    respond_to do |format|
      if @status.save
        format.html { redirect_to(@status, :notice => 'Status was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to(@status, :notice => 'Status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @status.errors, :status => :unprocessable_entity }
      end
    end
  end

  def post_to_twitter(status)
    TwitterUpdate.update do
      client = Twitter::Client.new(
                                   :consumer_key => ENV["TWITTER_CONSUMER_KEY"],
                                   :consumer_secret => ENV["TWITTER_CONSUMER_SECRET"],
                                   :oauth_token => ENV["TWITTER_OAUTH_KEY"],
                                   :oauth_token_secret => ENV["TWITTER_OAUTH_SECRET"])
      client.update(TwitterUpdate.new(status).message)
    end
  end
  
  private
  def login_required
    redirect_to new_session_path if session[:current_user_id].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= "#{@page_title} - " if @page_title %> Gitorious.org status</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="status,gitorious,uptime">
    <meta name="description" content="Uptime and current status for gitorious.org">
    <link href="/stylesheets/gitorious.css" media="screen,projection,handheld" type="text/css" rel="stylesheet">
  </head>
  <body>
    <div id="logo">
      <a href="http://gitorious.org/">
        <%=  image_tag("logo.png", :size => "180x51", :alt => "Gitorious") %>
      </a>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <div id="footer-links">
	<h3>Gitorious</h3>
	<ul>
	  <li><%= link_to("Public uptime report","http://stats.pingdom.com/83w3nssocvlk/265890", :title => "Public Pingdom report for gitorious.org") -%></li>
	</ul>
	<ul>
	  <li><a href="http://gitorious.org/">Gitorious.org</a></li>
	  <li><a href="http://gitorious.org/about">About Gitorious</a></li>
        </ul>
        <ul>
	  <li><a href="http://gitorious.org/about/faq">FAQ</a></li>
	  <li><a href="http://gitorious.org/contact">Contact</a></li>
	</ul>
	<ul>
	  <li><a href="http://groups.google.com/group/gitorious">Discussion group</a></li>
	  <li><a href="http://blog.gitorious.org">Blog</a></li>
	</ul>
      </div>
      <div class="clear"></div>
    </div>
    <script type="text/javascript">
      var _gaq=_gaq||[];_gaq.push(['_setAccount','UA-52238-5']);_gaq.push(['_trackPageview']);(function(d){var ga=d.createElement('script');ga.type='text/javascript';ga.async=true;ga.src=('https:'==d.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=d.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);})(document);
    </script>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>
      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <% Status.statuses.each do |status| %>
      <%= f.radio_button :status, status %>
      <label for="status_status_<%= status %>"><%= Status.status_text(status) %></label>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :post_to_twitter %>
    <%= f.check_box :post_to_twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/current.html.erb
<% @page_title = @status.title %>
<div id="status">
  <div class="status"><span class="<%= @status.status_text.downcase %>"><%= @status.status_text %></span></div>
  <h1><%= "<span>#{@created_at}</span>".html_safe if !@status.ok? %><%= @status.title %></h1>
  <%= "<p>#{@status.body}</p>".html_safe unless @status.body.blank? %>
  <% unless @problem.nil? %>
    <p id="problem">Up since <%= @created_at %> (<%= @problem.title %>)</p>
  <% end %>
</div>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.title %></td>
    <td><%= status.body %></td>
    <td><%= status.status %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @status.title %>
</p>

<p>
  <b>Body:</b>
  <%= @status.body %>
</p>

<p>
  <b>Status:</b>
  <%= @status.status %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>